export const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE score-partwise PUBLIC "-//Recordare//DTD MusicXML 4.0 Partwise//EN" "http://www.musicxml.org/dtds/partwise.dtd">
<score-partwise version="4.0">
  <work>
    <work-title>Untitled score</work-title>
    </work>
  <identification>
    <creator type="composer">Composer / arranger</creator>
    <encoding>
      <software>MuseScore Studio 4.7.3</software>
      <encoding-date>2026-06-27</encoding-date>
      <supports element="accidental" type="yes"/>
      <supports element="beam" type="yes"/>
      <supports element="print" attribute="new-page" type="no"/>
      <supports element="print" attribute="new-system" type="no"/>
      <supports element="stem" type="yes"/>
      </encoding>
    <miscellaneous>
      <miscellaneous-field name="partName">Bass Guitar</miscellaneous-field>
      </miscellaneous>
    </identification>
  <part-list>
    <score-part id="P1">
      <part-name print-object="no">Bass Guitar</part-name>
      <part-abbreviation print-object="no">B. Guit.</part-abbreviation>
      <score-instrument id="P1-I1">
        <instrument-name>Bass Guitar</instrument-name>
        <instrument-sound>pluck.bass</instrument-sound>
        </score-instrument>
      <midi-device id="P1-I1" port="1"></midi-device>
      <midi-instrument id="P1-I1">
        <midi-channel>1</midi-channel>
        <midi-program>35</midi-program>
        <volume>78.7402</volume>
        <pan>0</pan>
        </midi-instrument>
      </score-part>
    </part-list>
  <part id="P1">
    <measure number="1">
      <attributes>
        <divisions>2</divisions>
        <key>
          <fifths>0</fifths>
          </key>
        <time>
          <beats>4</beats>
          <beat-type>4</beat-type>
          </time>
        <clef>
          <sign>TAB</sign>
          </clef>
        <staff-details>
          <staff-lines>4</staff-lines>
          <staff-tuning line="1">
            <tuning-step>E</tuning-step>
            <tuning-octave>2</tuning-octave>
            </staff-tuning>
          <staff-tuning line="2">
            <tuning-step>A</tuning-step>
            <tuning-octave>2</tuning-octave>
            </staff-tuning>
          <staff-tuning line="3">
            <tuning-step>D</tuning-step>
            <tuning-octave>3</tuning-octave>
            </staff-tuning>
          <staff-tuning line="4">
            <tuning-step>G</tuning-step>
            <tuning-octave>3</tuning-octave>
            </staff-tuning>
          <staff-size>150</staff-size>
          </staff-details>
        <transpose>
          <diatonic>0</diatonic>
          <chromatic>0</chromatic>
          <octave-change>-1</octave-change>
          </transpose>
        </attributes>
      <direction placement="above" system="only-top">
        <direction-type>
          <rehearsal font-weight="bold" font-size="14">Verse</rehearsal>
          </direction-type>
        </direction>
      <note>
        <pitch>
          <step>E</step>
          <octave>2</octave>
          </pitch>
        <duration>2</duration>
        <voice>1</voice>
        <type>quarter</type>
        <stem>none</stem>
        <notations>
          <technical>
            <string>4</string>
            <fret>0</fret>
            </technical>
          </notations>
        </note>
      <note>
        <pitch>
          <step>E</step>
          <octave>2</octave>
          </pitch>
        <duration>2</duration>
        <voice>1</voice>
        <type>quarter</type>
        <stem>none</stem>
        <notations>
          <technical>
            <string>4</string>
            <fret>0</fret>
            </technical>
          </notations>
        </note>
      <note>
        <pitch>
          <step>E</step>
          <octave>2</octave>
          </pitch>
        <duration>4</duration>
        <voice>1</voice>
        <type>half</type>
        <stem>none</stem>
        <notations>
          <technical>
            <string>4</string>
            <fret>0</fret>
            </technical>
          </notations>
        </note>
      </measure>
    <measure number="2">
      <note>
        <pitch>
          <step>E</step>
          <octave>2</octave>
          </pitch>
        <duration>2</duration>
        <voice>1</voice>
        <type>quarter</type>
        <stem>none</stem>
        <notations>
          <technical>
            <string>4</string>
            <fret>0</fret>
            </technical>
          </notations>
        </note>
      <note>
        <pitch>
          <step>E</step>
          <octave>2</octave>
          </pitch>
        <duration>2</duration>
        <voice>1</voice>
        <type>quarter</type>
        <stem>none</stem>
        <notations>
          <technical>
            <string>4</string>
            <fret>0</fret>
            </technical>
          </notations>
        </note>
      <note>
        <pitch>
          <step>E</step>
          <octave>2</octave>
          </pitch>
        <duration>4</duration>
        <voice>1</voice>
        <type>half</type>
        <stem>none</stem>
        <notations>
          <technical>
            <string>4</string>
            <fret>0</fret>
            </technical>
          </notations>
        </note>
      </measure>
    <measure number="3">
      <note>
        <pitch>
          <step>E</step>
          <octave>2</octave>
          </pitch>
        <duration>2</duration>
        <voice>1</voice>
        <type>quarter</type>
        <stem>none</stem>
        <notations>
          <technical>
            <string>4</string>
            <fret>0</fret>
            </technical>
          </notations>
        </note>
      <note>
        <pitch>
          <step>E</step>
          <octave>2</octave>
          </pitch>
        <duration>2</duration>
        <voice>1</voice>
        <type>quarter</type>
        <stem>none</stem>
        <notations>
          <technical>
            <string>4</string>
            <fret>0</fret>
            </technical>
          </notations>
        </note>
      <note>
        <pitch>
          <step>E</step>
          <octave>2</octave>
          </pitch>
        <duration>4</duration>
        <voice>1</voice>
        <type>half</type>
        <stem>none</stem>
        <notations>
          <technical>
            <string>4</string>
            <fret>0</fret>
            </technical>
          </notations>
        </note>
      </measure>
    <measure number="4">
      <note>
        <pitch>
          <step>E</step>
          <octave>2</octave>
          </pitch>
        <duration>1</duration>
        <voice>1</voice>
        <type>eighth</type>
        <stem>none</stem>
        <notations>
          <technical>
            <string>4</string>
            <fret>0</fret>
            </technical>
          </notations>
        </note>
      <note>
        <pitch>
          <step>F</step>
          <octave>2</octave>
          </pitch>
        <duration>1</duration>
        <voice>1</voice>
        <type>eighth</type>
        <stem>none</stem>
        <notations>
          <technical>
            <string>4</string>
            <fret>1</fret>
            </technical>
          </notations>
        </note>
      <note>
        <pitch>
          <step>F</step>
          <alter>1</alter>
          <octave>2</octave>
          </pitch>
        <duration>1</duration>
        <voice>1</voice>
        <type>eighth</type>
        <stem>none</stem>
        <notations>
          <technical>
            <string>4</string>
            <fret>2</fret>
            </technical>
          </notations>
        </note>
      <note>
        <pitch>
          <step>G</step>
          <octave>2</octave>
          </pitch>
        <duration>1</duration>
        <voice>1</voice>
        <type>eighth</type>
        <stem>none</stem>
        <notations>
          <technical>
            <string>4</string>
            <fret>3</fret>
            </technical>
          </notations>
        </note>
      <note>
        <pitch>
          <step>G</step>
          <alter>1</alter>
          <octave>2</octave>
          </pitch>
        <duration>1</duration>
        <voice>1</voice>
        <type>eighth</type>
        <stem>none</stem>
        <notations>
          <technical>
            <string>4</string>
            <fret>4</fret>
            </technical>
          </notations>
        </note>
      <note>
        <pitch>
          <step>A</step>
          <octave>2</octave>
          </pitch>
        <duration>1</duration>
        <voice>1</voice>
        <type>eighth</type>
        <stem>none</stem>
        <notations>
          <technical>
            <string>3</string>
            <fret>0</fret>
            </technical>
          </notations>
        </note>
      <note>
        <pitch>
          <step>B</step>
          <alter>-1</alter>
          <octave>2</octave>
          </pitch>
        <duration>1</duration>
        <voice>1</voice>
        <type>eighth</type>
        <stem>none</stem>
        <notations>
          <technical>
            <string>3</string>
            <fret>1</fret>
            </technical>
          </notations>
        </note>
      <note>
        <pitch>
          <step>B</step>
          <octave>2</octave>
          </pitch>
        <duration>1</duration>
        <voice>1</voice>
        <type>eighth</type>
        <stem>none</stem>
        <notations>
          <technical>
            <string>3</string>
            <fret>2</fret>
            </technical>
          </notations>
        </note>
      </measure>
    <measure number="5">
      <note>
        <pitch>
          <step>E</step>
          <octave>2</octave>
          </pitch>
        <duration>2</duration>
        <voice>1</voice>
        <type>quarter</type>
        <stem>none</stem>
        <notations>
          <technical>
            <string>4</string>
            <fret>0</fret>
            </technical>
          </notations>
        </note>
      <note>
        <pitch>
          <step>E</step>
          <octave>2</octave>
          </pitch>
        <duration>2</duration>
        <voice>1</voice>
        <type>quarter</type>
        <stem>none</stem>
        <notations>
          <technical>
            <string>4</string>
            <fret>0</fret>
            </technical>
          </notations>
        </note>
      <note>
        <pitch>
          <step>E</step>
          <octave>2</octave>
          </pitch>
        <duration>4</duration>
        <voice>1</voice>
        <type>half</type>
        <stem>none</stem>
        <notations>
          <technical>
            <string>4</string>
            <fret>0</fret>
            </technical>
          </notations>
        </note>
      </measure>
    <measure number="6">
      <note>
        <pitch>
          <step>E</step>
          <octave>2</octave>
          </pitch>
        <duration>2</duration>
        <voice>1</voice>
        <type>quarter</type>
        <stem>none</stem>
        <notations>
          <technical>
            <string>4</string>
            <fret>0</fret>
            </technical>
          </notations>
        </note>
      <note>
        <pitch>
          <step>E</step>
          <octave>2</octave>
          </pitch>
        <duration>2</duration>
        <voice>1</voice>
        <type>quarter</type>
        <stem>none</stem>
        <notations>
          <technical>
            <string>4</string>
            <fret>0</fret>
            </technical>
          </notations>
        </note>
      <note>
        <pitch>
          <step>E</step>
          <octave>2</octave>
          </pitch>
        <duration>4</duration>
        <voice>1</voice>
        <type>half</type>
        <stem>none</stem>
        <notations>
          <technical>
            <string>4</string>
            <fret>0</fret>
            </technical>
          </notations>
        </note>
      </measure>
    <measure number="7">
      <note>
        <pitch>
          <step>E</step>
          <octave>2</octave>
          </pitch>
        <duration>2</duration>
        <voice>1</voice>
        <type>quarter</type>
        <stem>none</stem>
        <notations>
          <technical>
            <string>4</string>
            <fret>0</fret>
            </technical>
          </notations>
        </note>
      <note>
        <pitch>
          <step>E</step>
          <octave>2</octave>
          </pitch>
        <duration>2</duration>
        <voice>1</voice>
        <type>quarter</type>
        <stem>none</stem>
        <notations>
          <technical>
            <string>4</string>
            <fret>0</fret>
            </technical>
          </notations>
        </note>
      <note>
        <pitch>
          <step>E</step>
          <octave>2</octave>
          </pitch>
        <duration>4</duration>
        <voice>1</voice>
        <type>half</type>
        <stem>none</stem>
        <notations>
          <technical>
            <string>4</string>
            <fret>0</fret>
            </technical>
          </notations>
        </note>
      </measure>
    <measure number="8">
      <note>
        <pitch>
          <step>E</step>
          <octave>2</octave>
          </pitch>
        <duration>1</duration>
        <voice>1</voice>
        <type>eighth</type>
        <stem>none</stem>
        <notations>
          <technical>
            <string>4</string>
            <fret>0</fret>
            </technical>
          </notations>
        </note>
      <note>
        <pitch>
          <step>F</step>
          <octave>2</octave>
          </pitch>
        <duration>1</duration>
        <voice>1</voice>
        <type>eighth</type>
        <stem>none</stem>
        <notations>
          <technical>
            <string>4</string>
            <fret>1</fret>
            </technical>
          </notations>
        </note>
      <note>
        <pitch>
          <step>F</step>
          <alter>1</alter>
          <octave>2</octave>
          </pitch>
        <duration>1</duration>
        <voice>1</voice>
        <type>eighth</type>
        <stem>none</stem>
        <notations>
          <technical>
            <string>4</string>
            <fret>2</fret>
            </technical>
          </notations>
        </note>
      <note>
        <pitch>
          <step>G</step>
          <octave>2</octave>
          </pitch>
        <duration>1</duration>
        <voice>1</voice>
        <type>eighth</type>
        <stem>none</stem>
        <notations>
          <technical>
            <string>4</string>
            <fret>3</fret>
            </technical>
          </notations>
        </note>
      <note>
        <pitch>
          <step>G</step>
          <alter>1</alter>
          <octave>2</octave>
          </pitch>
        <duration>1</duration>
        <voice>1</voice>
        <type>eighth</type>
        <stem>none</stem>
        <notations>
          <technical>
            <string>4</string>
            <fret>4</fret>
            </technical>
          </notations>
        </note>
      <note>
        <pitch>
          <step>A</step>
          <octave>2</octave>
          </pitch>
        <duration>1</duration>
        <voice>1</voice>
        <type>eighth</type>
        <stem>none</stem>
        <notations>
          <technical>
            <string>3</string>
            <fret>0</fret>
            </technical>
          </notations>
        </note>
      <note>
        <pitch>
          <step>B</step>
          <alter>-1</alter>
          <octave>2</octave>
          </pitch>
        <duration>1</duration>
        <voice>1</voice>
        <type>eighth</type>
        <stem>none</stem>
        <notations>
          <technical>
            <string>3</string>
            <fret>1</fret>
            </technical>
          </notations>
        </note>
      <note>
        <pitch>
          <step>B</step>
          <octave>2</octave>
          </pitch>
        <duration>1</duration>
        <voice>1</voice>
        <type>eighth</type>
        <stem>none</stem>
        <notations>
          <technical>
            <string>3</string>
            <fret>2</fret>
            </technical>
          </notations>
        </note>
      </measure>
    <measure number="9">
      <direction placement="above" system="only-top">
        <direction-type>
          <rehearsal font-weight="bold" font-size="14">Chorus</rehearsal>
          </direction-type>
        </direction>
      <note>
        <pitch>
          <step>G</step>
          <octave>3</octave>
          </pitch>
        <duration>3</duration>
        <voice>1</voice>
        <type>quarter</type>
        <dot/>
        <stem>none</stem>
        <notations>
          <technical>
            <string>3</string>
            <fret>10</fret>
            </technical>
          </notations>
        </note>
      <note>
        <pitch>
          <step>G</step>
          <octave>3</octave>
          </pitch>
        <duration>3</duration>
        <voice>1</voice>
        <type>quarter</type>
        <dot/>
        <stem>none</stem>
        <notations>
          <technical>
            <string>3</string>
            <fret>10</fret>
            </technical>
          </notations>
        </note>
      <note>
        <pitch>
          <step>G</step>
          <octave>3</octave>
          </pitch>
        <duration>2</duration>
        <voice>1</voice>
        <type>quarter</type>
        <stem>none</stem>
        <notations>
          <technical>
            <string>3</string>
            <fret>10</fret>
            </technical>
          </notations>
        </note>
      </measure>
    <measure number="10">
      <note>
        <pitch>
          <step>A</step>
          <octave>3</octave>
          </pitch>
        <duration>3</duration>
        <voice>1</voice>
        <type>quarter</type>
        <dot/>
        <stem>none</stem>
        <notations>
          <technical>
            <string>3</string>
            <fret>12</fret>
            </technical>
          </notations>
        </note>
      <note>
        <pitch>
          <step>A</step>
          <octave>3</octave>
          </pitch>
        <duration>3</duration>
        <voice>1</voice>
        <type>quarter</type>
        <dot/>
        <stem>none</stem>
        <notations>
          <technical>
            <string>3</string>
            <fret>12</fret>
            </technical>
          </notations>
        </note>
      <note>
        <pitch>
          <step>A</step>
          <octave>3</octave>
          </pitch>
        <duration>2</duration>
        <voice>1</voice>
        <type>quarter</type>
        <stem>none</stem>
        <notations>
          <technical>
            <string>3</string>
            <fret>12</fret>
            </technical>
          </notations>
        </note>
      </measure>
    <measure number="11">
      <note>
        <pitch>
          <step>E</step>
          <octave>3</octave>
          </pitch>
        <duration>3</duration>
        <voice>1</voice>
        <type>quarter</type>
        <dot/>
        <stem>none</stem>
        <notations>
          <technical>
            <string>4</string>
            <fret>12</fret>
            </technical>
          </notations>
        </note>
      <note>
        <pitch>
          <step>E</step>
          <octave>3</octave>
          </pitch>
        <duration>3</duration>
        <voice>1</voice>
        <type>quarter</type>
        <dot/>
        <stem>none</stem>
        <notations>
          <technical>
            <string>4</string>
            <fret>12</fret>
            </technical>
          </notations>
        </note>
      <note>
        <pitch>
          <step>E</step>
          <octave>3</octave>
          </pitch>
        <duration>2</duration>
        <voice>1</voice>
        <type>quarter</type>
        <stem>none</stem>
        <notations>
          <technical>
            <string>4</string>
            <fret>12</fret>
            </technical>
          </notations>
        </note>
      </measure>
    <measure number="12">
      <note>
        <pitch>
          <step>C</step>
          <octave>3</octave>
          </pitch>
        <duration>3</duration>
        <voice>1</voice>
        <type>quarter</type>
        <dot/>
        <stem>none</stem>
        <notations>
          <technical>
            <string>4</string>
            <fret>8</fret>
            </technical>
          </notations>
        </note>
      <note>
        <pitch>
          <step>C</step>
          <octave>3</octave>
          </pitch>
        <duration>3</duration>
        <voice>1</voice>
        <type>quarter</type>
        <dot/>
        <stem>none</stem>
        <notations>
          <technical>
            <string>4</string>
            <fret>8</fret>
            </technical>
          </notations>
        </note>
      <note>
        <pitch>
          <step>C</step>
          <octave>3</octave>
          </pitch>
        <duration>2</duration>
        <voice>1</voice>
        <type>quarter</type>
        <stem>none</stem>
        <notations>
          <technical>
            <string>4</string>
            <fret>8</fret>
            </technical>
          </notations>
        </note>
      </measure>
    <measure number="13">
      <note>
        <pitch>
          <step>G</step>
          <octave>3</octave>
          </pitch>
        <duration>3</duration>
        <voice>1</voice>
        <type>quarter</type>
        <dot/>
        <stem>none</stem>
        <notations>
          <technical>
            <string>3</string>
            <fret>10</fret>
            </technical>
          </notations>
        </note>
      <note>
        <pitch>
          <step>G</step>
          <octave>3</octave>
          </pitch>
        <duration>3</duration>
        <voice>1</voice>
        <type>quarter</type>
        <dot/>
        <stem>none</stem>
        <notations>
          <technical>
            <string>3</string>
            <fret>10</fret>
            </technical>
          </notations>
        </note>
      <note>
        <pitch>
          <step>G</step>
          <octave>3</octave>
          </pitch>
        <duration>2</duration>
        <voice>1</voice>
        <type>quarter</type>
        <stem>none</stem>
        <notations>
          <technical>
            <string>3</string>
            <fret>10</fret>
            </technical>
          </notations>
        </note>
      </measure>
    <measure number="14">
      <note>
        <pitch>
          <step>A</step>
          <octave>3</octave>
          </pitch>
        <duration>3</duration>
        <voice>1</voice>
        <type>quarter</type>
        <dot/>
        <stem>none</stem>
        <notations>
          <technical>
            <string>3</string>
            <fret>12</fret>
            </technical>
          </notations>
        </note>
      <note>
        <pitch>
          <step>A</step>
          <octave>3</octave>
          </pitch>
        <duration>3</duration>
        <voice>1</voice>
        <type>quarter</type>
        <dot/>
        <stem>none</stem>
        <notations>
          <technical>
            <string>3</string>
            <fret>12</fret>
            </technical>
          </notations>
        </note>
      <note>
        <pitch>
          <step>A</step>
          <octave>3</octave>
          </pitch>
        <duration>2</duration>
        <voice>1</voice>
        <type>quarter</type>
        <stem>none</stem>
        <notations>
          <technical>
            <string>3</string>
            <fret>12</fret>
            </technical>
          </notations>
        </note>
      </measure>
    <measure number="15">
      <note>
        <pitch>
          <step>E</step>
          <octave>3</octave>
          </pitch>
        <duration>3</duration>
        <voice>1</voice>
        <type>quarter</type>
        <dot/>
        <stem>none</stem>
        <notations>
          <technical>
            <string>4</string>
            <fret>12</fret>
            </technical>
          </notations>
        </note>
      <note>
        <pitch>
          <step>E</step>
          <octave>3</octave>
          </pitch>
        <duration>3</duration>
        <voice>1</voice>
        <type>quarter</type>
        <dot/>
        <stem>none</stem>
        <notations>
          <technical>
            <string>4</string>
            <fret>12</fret>
            </technical>
          </notations>
        </note>
      <note>
        <pitch>
          <step>E</step>
          <octave>3</octave>
          </pitch>
        <duration>2</duration>
        <voice>1</voice>
        <type>quarter</type>
        <stem>none</stem>
        <notations>
          <technical>
            <string>4</string>
            <fret>12</fret>
            </technical>
          </notations>
        </note>
      </measure>
    <measure number="16">
      <note>
        <pitch>
          <step>C</step>
          <octave>3</octave>
          </pitch>
        <duration>3</duration>
        <voice>1</voice>
        <type>quarter</type>
        <dot/>
        <stem>none</stem>
        <notations>
          <technical>
            <string>4</string>
            <fret>8</fret>
            </technical>
          </notations>
        </note>
      <note>
        <pitch>
          <step>C</step>
          <octave>3</octave>
          </pitch>
        <duration>3</duration>
        <voice>1</voice>
        <type>quarter</type>
        <dot/>
        <stem>none</stem>
        <notations>
          <technical>
            <string>4</string>
            <fret>8</fret>
            </technical>
          </notations>
        </note>
      <note>
        <pitch>
          <step>C</step>
          <octave>3</octave>
          </pitch>
        <duration>2</duration>
        <voice>1</voice>
        <type>quarter</type>
        <stem>none</stem>
        <notations>
          <technical>
            <string>4</string>
            <fret>8</fret>
            </technical>
          </notations>
        </note>
      </measure>
    <measure number="17">
      <harmony print-frame="no">
        <root>
          <root-step>E</root-step>
          </root>
        <kind text="m">minor</kind>
        </harmony>
      <note>
        <pitch>
          <step>E</step>
          <octave>2</octave>
          </pitch>
        <duration>2</duration>
        <voice>1</voice>
        <type>quarter</type>
        <stem>none</stem>
        <notehead>slash</notehead>
        <notations>
          <technical>
            <string>4</string>
            <fret>0</fret>
            </technical>
          </notations>
        </note>
      <note>
        <pitch>
          <step>E</step>
          <octave>2</octave>
          </pitch>
        <duration>2</duration>
        <voice>1</voice>
        <type>quarter</type>
        <stem>none</stem>
        <notehead>slash</notehead>
        <notations>
          <technical>
            <string>4</string>
            <fret>0</fret>
            </technical>
          </notations>
        </note>
      <note>
        <pitch>
          <step>E</step>
          <octave>2</octave>
          </pitch>
        <duration>4</duration>
        <voice>1</voice>
        <type>half</type>
        <stem>none</stem>
        <notehead>slash</notehead>
        <notations>
          <technical>
            <string>4</string>
            <fret>0</fret>
            </technical>
          </notations>
        </note>
      </measure>
    <measure number="18">
      <harmony print-frame="no">
        <root>
          <root-step>E</root-step>
          </root>
        <kind text="m">minor</kind>
        </harmony>
      <note>
        <pitch>
          <step>E</step>
          <octave>2</octave>
          </pitch>
        <duration>2</duration>
        <voice>1</voice>
        <type>quarter</type>
        <stem>none</stem>
        <notehead>slash</notehead>
        <notations>
          <technical>
            <string>4</string>
            <fret>0</fret>
            </technical>
          </notations>
        </note>
      <note>
        <pitch>
          <step>E</step>
          <octave>2</octave>
          </pitch>
        <duration>2</duration>
        <voice>1</voice>
        <type>quarter</type>
        <stem>none</stem>
        <notehead>slash</notehead>
        <notations>
          <technical>
            <string>4</string>
            <fret>0</fret>
            </technical>
          </notations>
        </note>
      <note>
        <pitch>
          <step>E</step>
          <octave>2</octave>
          </pitch>
        <duration>4</duration>
        <voice>1</voice>
        <type>half</type>
        <stem>none</stem>
        <notehead>slash</notehead>
        <notations>
          <technical>
            <string>4</string>
            <fret>0</fret>
            </technical>
          </notations>
        </note>
      </measure>
    <measure number="19">
      <harmony print-frame="no">
        <root>
          <root-step>E</root-step>
          </root>
        <kind text="m">minor</kind>
        </harmony>
      <note>
        <pitch>
          <step>E</step>
          <octave>2</octave>
          </pitch>
        <duration>2</duration>
        <voice>1</voice>
        <type>quarter</type>
        <stem>none</stem>
        <notehead>slash</notehead>
        <notations>
          <technical>
            <string>4</string>
            <fret>0</fret>
            </technical>
          </notations>
        </note>
      <note>
        <pitch>
          <step>E</step>
          <octave>2</octave>
          </pitch>
        <duration>2</duration>
        <voice>1</voice>
        <type>quarter</type>
        <stem>none</stem>
        <notehead>slash</notehead>
        <notations>
          <technical>
            <string>4</string>
            <fret>0</fret>
            </technical>
          </notations>
        </note>
      <note>
        <pitch>
          <step>E</step>
          <octave>2</octave>
          </pitch>
        <duration>4</duration>
        <voice>1</voice>
        <type>half</type>
        <stem>none</stem>
        <notehead>slash</notehead>
        <notations>
          <technical>
            <string>4</string>
            <fret>0</fret>
            </technical>
          </notations>
        </note>
      </measure>
    <measure number="20">
      <harmony print-frame="no">
        <root>
          <root-step>E</root-step>
          </root>
        <kind text="m">minor</kind>
        </harmony>
      <note>
        <pitch>
          <step>E</step>
          <octave>2</octave>
          </pitch>
        <duration>2</duration>
        <voice>1</voice>
        <type>quarter</type>
        <stem>none</stem>
        <notehead>slash</notehead>
        <notations>
          <technical>
            <string>4</string>
            <fret>0</fret>
            </technical>
          </notations>
        </note>
      <note>
        <pitch>
          <step>E</step>
          <octave>2</octave>
          </pitch>
        <duration>2</duration>
        <voice>1</voice>
        <type>quarter</type>
        <stem>none</stem>
        <notehead>slash</notehead>
        <notations>
          <technical>
            <string>4</string>
            <fret>0</fret>
            </technical>
          </notations>
        </note>
      <note>
        <pitch>
          <step>E</step>
          <octave>2</octave>
          </pitch>
        <duration>4</duration>
        <voice>1</voice>
        <type>half</type>
        <stem>none</stem>
        <notehead>slash</notehead>
        <notations>
          <technical>
            <string>4</string>
            <fret>0</fret>
            </technical>
          </notations>
        </note>
      </measure>
    <measure number="21">
      <harmony print-frame="no">
        <root>
          <root-step>E</root-step>
          </root>
        <kind text="m">minor</kind>
        </harmony>
      <note>
        <pitch>
          <step>E</step>
          <octave>2</octave>
          </pitch>
        <duration>8</duration>
        <voice>1</voice>
        <type>whole</type>
        <stem>none</stem>
        <notehead>slash</notehead>
        <notations>
          <technical>
            <string>4</string>
            <fret>0</fret>
            </technical>
          </notations>
        </note>
      <barline location="right">
        <bar-style>light-heavy</bar-style>
        </barline>
      </measure>
    </part>
  </score-partwise>
`